[book]
authors = ["x06lan"]
language = "en"
multilingual = false
src = "src"
title = "something"

[output.html]
#mathjax-support = true

[output.html.playground]
editable = true

[preprocessor.katex]
command = "./mdbook-katex"

