[book]
authors = ["x06lan"]
language = "en"
multilingual = false
src = "src"
title = "something"

[output.html]
#mathjax-support = true
preferred-dark-theme = "navy"
copy-fonts = true
curly-quotes = true

git-repository-url = "https://github.com/x06lan/mdbook"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js", "mermaid.min.js", "mermaid-init.js"]


[output.html.fold]
enable = true # whether or not to enable section folding
level = 0

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.playground]
editable = true
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = false     # displays line numbers for editable code

[preprocessor.katex]
command = "./mdbook-katex"

#[preprocessor.graphviz]
#command = "mdbook-graphviz"
#output-to-file = false # defaults to false, change to true to create SVG files instead of rendering them inline

[preprocessor.mermaid]
command = "./mdbook-mermaid"

